// $game(r a p)color(1-17)_number(1-403)
/*
Each achievement is color-coded based on the requirements for unlocking their respective secrets:
Tan: Random/Miscellaneous unlocks
Tan with blood stain: Mom's Heart/It Lives! on Hard unlocks
Olive-Green: character unlocks
Dark Red: Mom's Heart/Womb ending unlocks
Grey: Isaac unlocks
Black: Satan unlocks
Dark Blue: ??? unlocks
Purple: The Lamb unlocks
Pale Green: Boss Rush unlocks
Pale Blue: Hush unlocks
Orange: Greed Mode unlocks
Orange with blood stain: Greedier mode unlocks
White: Delirium unlocks
Red: Mega Satan unlocks/accomplishments
Dark Yellow: All Hard Mode marks unlocks
Bright Yellow: Greed Donation Machine unlocks
Bluish Purple: Challenge unlocks
Despite being a Boss Rush unlock for Lazarus, Missing No. Missing No.'s achievement color is bluish purple, a color normally used for challenge-related unlocks.
*/
class ach {
  constructor(num, tle, dsc, img, lnk) {
    this.name = tle;
    this.image = img;
    this.link = lnk;
    this.unlock = dsc;
    this.number = num;
  }
}
function tblInit() {
  var achievements = [];
  var links = [
    "https://bindingofisaacrebirth.fandom.com/wiki/Magdalene",
    "https://bindingofisaacrebirth.fandom.com/wiki/Cain",
    "https://bindingofisaacrebirth.fandom.com/wiki/Judas",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Womb",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Harbingers",
    "https://bindingofisaacrebirth.fandom.com/wiki/Cube_of_Meat",
    "https://bindingofisaacrebirth.fandom.com/wiki/Book_of_Revelations",
    "https://bindingofisaacrebirth.fandom.com/wiki/Transcendence",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Nail",
    "https://bindingofisaacrebirth.fandom.com/wiki/A_Quarter",
    "https://bindingofisaacrebirth.fandom.com/wiki/Dr._Fetus",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Small_Rock",
    "https://bindingofisaacrebirth.fandom.com/wiki/Monstro%27s_Tooth",
    "https://bindingofisaacrebirth.fandom.com/wiki/Little_Chubby",
    "https://bindingofisaacrebirth.fandom.com/wiki/Loki%27s_Horns",
    "https://bindingofisaacrebirth.fandom.com/wiki/Steven",
    "https://bindingofisaacrebirth.fandom.com/wiki/C.H.A.D.",
    "https://bindingofisaacrebirth.fandom.com/wiki/Gish",
    "https://bindingofisaacrebirth.fandom.com/wiki/Super_Bandage",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Relic",
    "https://bindingofisaacrebirth.fandom.com/wiki/Sack_of_Pennies",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Book_of_Sin",
    "https://bindingofisaacrebirth.fandom.com/wiki/Little_Gish",
    "https://bindingofisaacrebirth.fandom.com/wiki/Little_Steven",
    "https://bindingofisaacrebirth.fandom.com/wiki/Little_C.H.A.D.",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Gamekid",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Halo",
    "https://bindingofisaacrebirth.fandom.com/wiki/Mr._Mega",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_D6",
    "https://bindingofisaacrebirth.fandom.com/wiki/Scissors",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Parasite",
    "https://bindingofisaacrebirth.fandom.com/wiki/%3F%3F%3F_(Character)",
    "pass",
    "https://bindingofisaacrebirth.fandom.com/wiki/It_Lives",
    "https://bindingofisaacrebirth.fandom.com/wiki/Mom%27s_Contacts",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Necronomicon",
    "pass",
    "pass",
    "pass",
    "pass",
    "pass",
    "https://bindingofisaacrebirth.fandom.com/wiki/Eve",
    "https://bindingofisaacrebirth.fandom.com/wiki/Mom%27s_Knife",
    "https://bindingofisaacrebirth.fandom.com/wiki/Razor_Blade",
    "https://bindingofisaacrebirth.fandom.com/wiki/Guardian_Angel",
    "https://bindingofisaacrebirth.fandom.com/wiki/Bomb_Bag",
    "https://bindingofisaacrebirth.fandom.com/wiki/Demon_Baby",
    "https://bindingofisaacrebirth.fandom.com/wiki/Forget_Me_Now",
    "https://bindingofisaacrebirth.fandom.com/wiki/D20",
    "https://bindingofisaacrebirth.fandom.com/wiki/Celtic_Cross",
    "https://bindingofisaacrebirth.fandom.com/wiki/Abel",
    "https://bindingofisaacrebirth.fandom.com/wiki/Curved_Horn",
    "https://bindingofisaacrebirth.fandom.com/wiki/Sacrificial_Dagger",
    "https://bindingofisaacrebirth.fandom.com/wiki/Bloody_Lust",
    "https://bindingofisaacrebirth.fandom.com/wiki/Bloody_Penny",
    "https://bindingofisaacrebirth.fandom.com/wiki/Blood_Rights",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Polaroid",
    "https://bindingofisaacrebirth.fandom.com/wiki/Dad%27s_Key",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Candle",
    "https://bindingofisaacrebirth.fandom.com/wiki/Burnt_Penny",
    "https://bindingofisaacrebirth.fandom.com/wiki/Lucky_Toe",
    "https://bindingofisaacrebirth.fandom.com/wiki/Epic_Fetus",
    "https://bindingofisaacrebirth.fandom.com/wiki/SMB_Super_Fan",
    "https://bindingofisaacrebirth.fandom.com/wiki/Counterfeit_Penny",
    "https://bindingofisaacrebirth.fandom.com/wiki/Guppy%27s_Hair_Ball",
    "https://bindingofisaacrebirth.fandom.com/wiki/Conquest",
    "https://bindingofisaacrebirth.fandom.com/wiki/Samson",
    "https://bindingofisaacrebirth.fandom.com/wiki/Triachnid",
    "pass",
    "https://bindingofisaacrebirth.fandom.com/wiki/Isaac%27s_Head",
    "https://bindingofisaacrebirth.fandom.com/wiki/Maggy%27s_Faith",
    "https://bindingofisaacrebirth.fandom.com/wiki/Judas%27_Tongue",
    "https://bindingofisaacrebirth.fandom.com/wiki/%3F%3F%3F%27s_Soul",
    "https://bindingofisaacrebirth.fandom.com/wiki/Samson%27s_Lock",
    "https://bindingofisaacrebirth.fandom.com/wiki/Cain%27s_Eye",
    "https://bindingofisaacrebirth.fandom.com/wiki/Eve%27s_Bird_Foot",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Left_Hand",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Negative",
    "https://bindingofisaacrebirth.fandom.com/wiki/Azazel",
    "https://bindingofisaacrebirth.fandom.com/wiki/Lazarus",
    "https://bindingofisaacrebirth.fandom.com/wiki/Eden",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Lost",
    "pass",
    "pass",
    "https://bindingofisaacrebirth.fandom.com/wiki/Lucky_Rock",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Cellar",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Catacombs",
    "https://bindingofisaacrebirth.fandom.com/wiki/Necropolis",
    "https://bindingofisaacrebirth.fandom.com/wiki/Runes",
    "https://bindingofisaacrebirth.fandom.com/wiki/Runes",
    "https://bindingofisaacrebirth.fandom.com/wiki/Runes",
    "https://bindingofisaacrebirth.fandom.com/wiki/Runes",
    "https://bindingofisaacrebirth.fandom.com/wiki/Runes",
    "https://bindingofisaacrebirth.fandom.com/wiki/Runes",
    "https://bindingofisaacrebirth.fandom.com/wiki/Runes",
    "https://bindingofisaacrebirth.fandom.com/wiki/Runes",
    "https://bindingofisaacrebirth.fandom.com/wiki/Chaos_Card",
    "https://bindingofisaacrebirth.fandom.com/wiki/Credit_Card",
    "https://bindingofisaacrebirth.fandom.com/wiki/Rules_Card",
    "https://bindingofisaacrebirth.fandom.com/wiki/A_Card_Against_Humanity",
    "https://bindingofisaacrebirth.fandom.com/wiki/Swallowed_Penny",
    "https://bindingofisaacrebirth.fandom.com/wiki/Robo-Baby_2.0",
    "https://bindingofisaacrebirth.fandom.com/wiki/Death%27s_Touch",
    "https://bindingofisaacrebirth.fandom.com/wiki/Tech.5",
    "https://bindingofisaacrebirth.fandom.com/wiki/Missing_No.",
    "https://bindingofisaacrebirth.fandom.com/wiki/Isaac%27s_Tears",
    "https://bindingofisaacrebirth.fandom.com/wiki/Guillotine",
    "https://bindingofisaacrebirth.fandom.com/wiki/Judas%27_Shadow",
    "https://bindingofisaacrebirth.fandom.com/wiki/Maggy%27s_Bow",
    "https://bindingofisaacrebirth.fandom.com/wiki/Cain%27s_Other_Eye",
    "https://bindingofisaacrebirth.fandom.com/wiki/Black_Lipstick",
    "https://bindingofisaacrebirth.fandom.com/wiki/Eve%27s_Mascara",
    "https://bindingofisaacrebirth.fandom.com/wiki/Fate",
    "https://bindingofisaacrebirth.fandom.com/wiki/%3F%3F%3F%27s_Only_Friend",
    "https://bindingofisaacrebirth.fandom.com/wiki/Samson%27s_Chains",
    "https://bindingofisaacrebirth.fandom.com/wiki/Lazarus%27_Rags",
    "https://bindingofisaacrebirth.fandom.com/wiki/Broken_Ankh",
    "https://bindingofisaacrebirth.fandom.com/wiki/Store_Credit",
    "https://bindingofisaacrebirth.fandom.com/wiki/Pandora%27s_Box",
    "https://bindingofisaacrebirth.fandom.com/wiki/Suicide_King",
    "https://bindingofisaacrebirth.fandom.com/wiki/Blank_Card",
    "https://bindingofisaacrebirth.fandom.com/wiki/Book_of_Secrets",
    "https://bindingofisaacrebirth.fandom.com/wiki/Mysterious_Paper",
    "https://bindingofisaacrebirth.fandom.com/wiki/Mystery_Sack",
    "https://bindingofisaacrebirth.fandom.com/wiki/Undefined",
    "https://bindingofisaacrebirth.fandom.com/wiki/Satanic_Bible",
    "https://bindingofisaacrebirth.fandom.com/wiki/Daemon%27s_Tail",
    "https://bindingofisaacrebirth.fandom.com/wiki/Abaddon",
    "https://bindingofisaacrebirth.fandom.com/wiki/Isaac%27s_Heart",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Mind",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Body",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Soul",
    "https://bindingofisaacrebirth.fandom.com/wiki/D100",
    "https://bindingofisaacrebirth.fandom.com/wiki/Blue_Map",
    "https://bindingofisaacrebirth.fandom.com/wiki/There%27s_Options",
    "https://bindingofisaacrebirth.fandom.com/wiki/Black_Candle",
    "https://bindingofisaacrebirth.fandom.com/wiki/Red_Candle",
    "https://bindingofisaacrebirth.fandom.com/wiki/Stop_Watch",
    "https://bindingofisaacrebirth.fandom.com/wiki/Wire_Coat_Hanger",
    "https://bindingofisaacrebirth.fandom.com/wiki/Ipecac",
    "https://bindingofisaacrebirth.fandom.com/wiki/Experimental_Treatment",
    "https://bindingofisaacrebirth.fandom.com/wiki/Krampus",
    "https://bindingofisaacrebirth.fandom.com/wiki/Head_of_Krampus",
    "https://bindingofisaacrebirth.fandom.com/wiki/Cube_of_Meat#Methods_to_create_a_Super_Meat_Boy",
    "https://bindingofisaacrebirth.fandom.com/wiki/Butter_Bean",
    "https://bindingofisaacrebirth.fandom.com/wiki/Little_Baggy",
    "https://bindingofisaacrebirth.fandom.com/wiki/Blood_Bag",
    "https://bindingofisaacrebirth.fandom.com/wiki/D4",
    "https://bindingofisaacrebirth.fandom.com/wiki/Missing_Poster",
    "https://bindingofisaacrebirth.fandom.com/wiki/Rubber_Cement",
    "https://bindingofisaacrebirth.fandom.com/wiki/Donation_machine",
    "https://bindingofisaacrebirth.fandom.com/wiki/Donation_machine",
    "https://bindingofisaacrebirth.fandom.com/wiki/Donation_machine",
    "https://bindingofisaacrebirth.fandom.com/wiki/Donation_machine",
    "https://bindingofisaacrebirth.fandom.com/wiki/Angel",
    "https://bindingofisaacrebirth.fandom.com/wiki/Godhead",
    "https://bindingofisaacrebirth.fandom.com/wiki/Darkness_Falls",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Tank",
    "https://bindingofisaacrebirth.fandom.com/wiki/Solar_System",
    "https://bindingofisaacrebirth.fandom.com/wiki/Suicide_King_(Challenge)",
    "https://bindingofisaacrebirth.fandom.com/wiki/Cat_Got_Your_Tongue",
    "https://bindingofisaacrebirth.fandom.com/wiki/Demo_Man",
    "https://bindingofisaacrebirth.fandom.com/wiki/Cursed!",
    "https://bindingofisaacrebirth.fandom.com/wiki/Glass_Cannon_(Challenge)",
    "https://bindingofisaacrebirth.fandom.com/wiki/The_Family_Man",
    "https://bindingofisaacrebirth.fandom.com/wiki/Purist",
    "https://bindingofisaacrebirth.fandom.com/wiki/Babies",
    "https://bindingofisaacrebirth.fandom.com/wiki/Babies",
    "https://bindingofisaacrebirth.fandom.com/wiki/Babies",
    "https://bindingofisaacrebirth.fandom.com/wiki/Babies",
    "https://bindingofisaacrebirth.fandom.com/wiki/Babies",
    "https://bindingofisaacrebirth.fandom.com/wiki/Babies",
    "https://bindingofisaacrebirth.fandom.com/wiki/Babies",
    "https://bindingofisaacrebirth.fandom.com/wiki/Babies",
    "https://bindingofisaacrebirth.fandom.com/wiki/Babies",
    "https://bindingofisaacrebirth.fandom.com/wiki/Babies",
    "https://bindingofisaacrebirth.fandom.com/wiki/Babies",
    "https://bindingofisaacrebirth.fandom.com/wiki/Beelzebub"
  ];
  var png = [
    "./gfx/3chr/magdalene.png",
    "./gfx/3chr/cain.png",
    "./gfx/3chr/judas.png",
    "./gfx/4heart/the womb.png",
    "./gfx/1misc/the harbingers.png",
    "./gfx/1misc/a cube of meat.png",
    "./gfx/1misc/the book of revelations.png",
    "./gfx/4heart/a noose.png",
    "./gfx/9rush/the nail.png",
    "./gfx/4heart/a quarter.png",
    "./gfx/4heart/a fetus in a jar.png",
    "./gfx/1misc/a small rock.png",
    "./gfx/1misc/monstro\'s tooth.png",
    "./gfx/1misc/lil\' chubby.png",
    "./gfx/1misc/loki\'s horns.png",
    "./gfx/1misc/something from the future.png",
    "./gfx/1misc/something cute.png",
    "./gfx/1misc/something sticky.png",
    "./gfx/1misc/a bandage.png",
    "./gfx/5isaac/a cross.png",
    "./gfx/5isaac/a bag of pennies.png",
    "./gfx/1misc/the book of sin.png",
    "./gfx/1misc/little gish.png",
    "./gfx/1misc/little steven.png",
    "./gfx/1misc/little c\.h\.a\.d\..png",
    "./gfx/1misc/a gamekid.png",
    "./gfx/1misc/a halo.png",
    "./gfx/1misc/mr\. mega.png",
    "./gfx/5isaac/the d6.png",
    "./gfx/1misc/the scissors.png",
    "./gfx/1misc/the parasite.png",
    "./gfx/3chr/blue baby character.png",
    "./gfx/4heart/everything is terrible!!!.png",
    "./gfx/4heart/it lives!.png",
    "./gfx/1misc/mom\'s contact.png",
    "./gfx/1misc/the necronomicon.png",
    "./gfx/15marks/basement boy.png",
    "./gfx/15marks/spelunker boy.png",
    "./gfx/15marks/dark boy.png",
    "./gfx/15marks/mama\'s boy.png",
    "./gfx/15marks/golden god!.png",
    "./gfx/3chr/eve.png",
    "./gfx/6satan/mom\'s knife.png",
    "./gfx/6satan/the razor.png",
    "./gfx/6satan/guardian angel.png",
    "./gfx/6satan/a bag of bombs.png",
    "./gfx/8lamb/demon baby.png",
    "./gfx/6satan/forget me now.png",
    "./gfx/7baby/the d20.png",
    "./gfx/7baby/celtic cross.png",
    "./gfx/8lamb/abel.png",
    "./gfx/8lamb/curved horn.png",
    "./gfx/7baby/sacrificial dagger.png",
    "./gfx/5isaac/bloody lust.png",
    "./gfx/7baby/blood penny.png",
    "./gfx/6satan/blood rights.png",
    "./gfx/5isaac/the polaroid.png",
    "./gfx/1misc/dad\'s key.png",
    "./gfx/1misc/blue candle.png",
    "./gfx/17trial/burnt penny.png",
    "./gfx/1misc/lucky toe.png",
    "./gfx/17trial/epic fetus.png",
    "./gfx/17trial/smb super fan.png",
    "./gfx/1misc/counterfeit coin.png",
    "./gfx/1misc/guppy\'s hairball.png",
    "./gfx/1misc/a forgotten horseman.png",
    "./gfx/3chr/samson.png",
    "./gfx/1misc/something icky.png",
    "./gfx/15marks/!platinum god!.png",
    "./gfx/9rush/isaac\'s head.png",
    "./gfx/8lamb/maggy\'s faith.png",
    "./gfx/6satan/judas\' tongue.png",
    "./gfx/8lamb/blue baby\'s soul.png",
    "./gfx/8lamb/samson\'s lock.png",
    "./gfx/7baby/cain\'s eye.png",
    "./gfx/5isaac/eve\'s bird foot.png",
    "./gfx/7baby/the left hand.png",
    "./gfx/6satan/the negative.png",
    "./gfx/3chr/azazel.png",
    "./gfx/3chr/lazarus.png",
    "./gfx/3chr/eden.png",
    "./gfx/3chr/the lost.png",
    "./gfx/15marks/dead boy.png",
    "./gfx/15marks/the real platinum god.png",
    "./gfx/1misc/lucky rock.png",
    "./gfx/1misc/the cellar.png",
    "./gfx/1misc/the catacombs.png",
    "./gfx/1misc/the necropolis.png",
    "./gfx/17trial/rune of hagalaz.png",
    "",
    "",
  ];
  var label = [
    "Magdalene",
    "Cain",
    "Judas",
    "The Womb",
    "The Harbingers",
    "A Cube of Meat",
    "The Book of Revelations",
    "A Noose",
    "The Nail",
    "A Quarter",
    "A Fetus in a Jar",
    "A Small Rock",
    "Monstro's Tooth",
    "Lil' Chubby",
    "Loki's Horns",
    "Something From The Future",
    "Something Cute",
    "Something Sticky",
    "A Bandage",
    "A Cross",
    "A Bag of Pennies",
    "The Book of Sin",
    "Little Gish",
    "Little Steven",
    "Little C.H.A.D.",
    "A Gamekid",
    "A Halo",
    "Mr. Mega",
    "The D6",
    "The Scissors",
    "The Parasite",
    "???",
    "Everything Is Terrible!!!",
    "It Lives!",
    "Mom's Contact",
    "The Necronomicon",
    "Basement Boy",
    "Spelunker Boy",
    "Dark Boy",
    "Mama's Boy",
    "Golden God!",
    "Eve",
    "Mom's Knife",
    "The Razor",
    "Guardian Angel",
    "A Bag of Bombs",
    "Demon Baby",
    "Forget Me Now",
    "The D20",
    "Celtic Cross",
    "Abel",
    "Curved Horn",
    "Sacrificial Dagger",
    "Bloody Lust",
    "Blood Penny",
    "Blood Rights",
    "The Polaroid",
    "Dad's Key",
    "Blue Candle",
    "Burnt Penny",
    "Lucky Toe",
    "Epic Fetus",
    "SMB Super Fan",
    "Counterfeit Coin",
    "Guppy's Hairball",
    "A Forgotten Horseman",
    "Samson",
    "Something Icky",
    "!Platinum God!",
    "Isaac's Head",
    "Maggy's Faith",
    "Judas' Tongue",
    "???'s Soul",
    "Samson's Lock",
    "Cain's Eye",
    "Eve's Bird Foot",
    "The Left Hand",
    "The Negative",
    "Azazel",
    "Lazarus",
    "Eden",
    "The Lost",
    "Dead Boy",
    "The Real Platinum God",
    "Lucky Rock",
    "The Cellar",
    "The Catacombs",
    "The Necropolis",
    "Rune of Hagalaz",
  ];
  var lock = [
    "Have 7 or more red heart containers at one time",
    "Hold 55 coins at one time",
    "Defeat Satan",
    "Defeat Mom",
    "Defeat Mom",
    "Defeat Mom",
    "Defeat a Harbinger",
    "Defeat Mom's Heart 3 times",
    "Complete the Boss Rush as Azazel",
    "Defeat Mom's Heart 8 times",
    "Defeat Mom's Heart 9 times",
    "Destroy 100 tinted rocks",
    "Beat chapter 1",
    "Beat chapter 2",
    "Defeat Lokii",
    "Beat The Basement 40 times",
    "Beat chapter 2 30 times",
    "Beat chapter 3 20 times",
    "Get a Super Bandage Girl by picking up 4 [Ball of Bandages] in a run",
    "Defeat Isaac as Magdalene",
    "Defeat Isaac as Cain",
    "Defeat all 7 deadly sins",
    "Defeat Gish",
    "Defeat Steven",
    "Defeat C.H.A.D.",
    "Visit 10 Arcades",
    "Defeat Mom, Mom's Heart or It Lives using The Bible",
    "Destroy 10 tinted rocks",
    "Defeat Isaac as ???",
    "Die 100 times",
    "Pick up any 2 of the following items in a run: [Bob's Rotten Head], [Dead Cat], [Cricket's Head], [Tammy's Head]",
    "Defeat Mom's Heart 10 times",
    "Defeat Mom's Heart 5 times",
    "Defeat Mom's Heart 11 times",
    "Obtain 3 items from the [Yes Mother?] collection in a run",
    "Use [XIII - Death] 4 times",
    "Beat chapter 1 without taking damage",
    "Beat chapter 2 without taking damage",
    "Beat chapter 3 without taking damage",
    "Beat chapter 4 without taking damage",
    "Defeat ??? and The Lamb",
    "Don't pick up any hearts for 2 floors in a row",
    "Defeat Satan as Isaac",
    "Defeat Satan as Eve",
    "Defeat Satan as Magdalene",
    "Defeat Satan as Cain",
    "Defeat The Lamb as Azazel",
    "Defeat Satan as ???",
    "Defeat ??? as Isaac",
    "Defeat ??? as Magdalene",
    "Defeat The Lamb as Cain",
    "Defeat The Lamb as Judas",
    "Defeat ??? as Eve",
    "Defeat Isaac as Samson",
    "Defeat ??? as Samson",
    "Defeat Satan as Samson",
    "Defeat Isaac 5 times",
    "Pick up both Key Pieces from the Angels in a run",
    "Donate 900 coins to the Donation Machine",
    "Complete [Beans!] Challenge #13",
    "Blow up 20 Shopkeepers",
    "Complete [The Family Man] Challenge #19",
    "Complete [It's in the Cards] Challenge #14",
    "Play the Shell Game 100 times",
    "Obtain 3 items from the [Guppy] collection in a run",
    "Take 10 items from Angel Rooms",
    "Complete 2 floors in a row without taking damage",
    "Defeat Isaac 10 times",
    "Collect all non-DLC items, secrets, and endings in the game, barring The Lost and its 6 unlockable items",
    "Complete the Boss Rush as Isaac",
    "Defeat The Lamb as Magdalene",
    "Defeat Satan as Judas",
    "Defeat The Lamb as ???",
    "Defeat The Lamb as Samson",
    "Defeat ??? as Cain",
    "Defeat Isaac as Eve",
    "Defeat ??? as Judas, or defeat Ultra Pride (as any character)",
    "Defeat Satan 5 times",
    "Make 3 devil deals in a run",
    "Have 4 or more Soul Hearts at a time",
    "Complete chapter 4",
    "Die in a Sacrifice Room while holding [Missing Poster]",
    "Complete chapter 6 without taking damage",
    "Collect every non-DLC item and ending",
    "Destroy 100 rocks",
    "Beat all bosses that can appear in The Basement",
    "Beat all bosses that can appear in The Caves",
    "Beat all bosses that can appear in The Depths",
    "Complete [Pitch Black] Challenge #1",
  ];
  for (i = 0; i < label.length; i++) {
    var ah = {};
    var zn = "$ach" + i;
    ah[zn] = new ach(i+1, label[i], lock[i], png[i], links[i])
    achievements.push(ah[zn]);
  }
  var x;
  for (x of achievements) {
    achLoop(x);
  }
}
function achLoop(y) {
  let tbl = document.getElementById('isaac');
  let row = tbl.insertRow(-1);
  let cellA = row.insertCell(0);
  let cellB = row.insertCell(1);
  let cellC = row.insertCell(2);
  if (y.link != 'pass') {
    cellA.innerHTML = '<a href="'+y.link+'" title="'+y.name+'" id="'+y.number+'"><img src="'+y.image+'" alt="'+y.name+'" decoding="async" height="64" width="64"></a>';
  } else {
    cellA.innerHTML = '<img src="'+y.image+'" alt="'+y.name+'" title="'+y.name+'" decoding="async" height="64" width="64">'
  }
  cellB.innerHTML = y.unlock;
  cellC.innerHTML = y.number;
}
tblInit();
